/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as PoliticaDeCookiesRouteImport } from './routes/politica-de-cookies'
import { Route as IndexRouteImport } from './routes/index'

const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeCookiesRoute = PoliticaDeCookiesRouteImport.update({
  id: '/politica-de-cookies',
  path: '/politica-de-cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politica-de-cookies': typeof PoliticaDeCookiesRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/politica-de-cookies' | '/politica-de-privacidad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/politica-de-cookies' | '/politica-de-privacidad'
  id: '__root__' | '/' | '/politica-de-cookies' | '/politica-de-privacidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticaDeCookiesRoute: typeof PoliticaDeCookiesRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-cookies': {
      id: '/politica-de-cookies'
      path: '/politica-de-cookies'
      fullPath: '/politica-de-cookies'
      preLoaderRoute: typeof PoliticaDeCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticaDeCookiesRoute: PoliticaDeCookiesRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
